### ISSUE TITLE
is sources.react.props() method supposed to work for isolated/selected components?

### ISSUE THREAD

**Issue by wclr** [cyclejs/react#12]
react source's `props()` method gets Root component props stream for any selected source.

```ts
sources.react.select(sel).props() // gets root component props stream not selected by `sel`
```

Is it by design? It is logical to propose that it should provide props stream for a selected component.

@staltz

**Comment by staltz** [comment]
I could be wrong, because your question makes sense, but I believe it is by design, because the `props$` refers to the props of the Cycle.js component converted to a React component, it doesn't refer to the props of a hyperscript-created ReactElement from inside the Cycle.js component.

Example:

```js
const App = makeComponent(main);
// App is a React component
// main is a Cycle component

render(h(App, {name: 'alice', age: 20}), document.getElementById('app'));
```

`props$` is a stream of objects such as `{name: 'alice', age: 20}`.

**Comment by wclr** [comment]
Yes, I see it from the code that root props stream propagated to newly created sources. Don't you think that it could be useful and more expected to provide props of a selected component? And to access root component props there should be some other API for example `react.select('root')` (though it usually refers to isolated root in DOM driver).

I believe there is no API to get changes of the component rendered (like `DOMSource.element()`), but it should be useful.

**Comment by staltz** [comment]
Well, if your component `main` (as per example code above) creates `childProps` and passes that to some child ReactElement, why would you need to read it from `sources`? You can read it through other means (the same means you used to create `childProps`). `ReactSource` should be concerned only with providing access to external events/data that aren't available to you inside `main`, i.e. user events and externally-passed `props`.

**Comment by wclr** [comment]
Yes, I believe you are right about other means. So will close it.
